# Generated by Django 5.1.6 on 2025-03-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
